services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: storytime-backend
    environment:
      - NODE_ENV=production
    volumes:
      - ./uploads:/app/uploads
      - ./backend/database:/app/database
    ports:
      - "8081:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:8080/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - storytime-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: storytime-frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - storytime-network

networks:
  storytime-network:
    driver: bridge